//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Specifications = new HashSet<Specification>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> Category { get; set; }
        public Nullable<System.Guid> CategoryID { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual ICollection<Specification> Specifications { get; set; }
    }
}
