//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specification
    {
        public Specification()
        {
            this.OrdersProducts = new HashSet<OrdersProduct>();
        }
    
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ProductID { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual ICollection<OrdersProduct> OrdersProducts { get; set; }
        public virtual Product Product { get; set; }
    }
}
