//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.AppointmentReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Appointment", Namespace="http://schemas.datacontract.org/2004/07/Common", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Appointment : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppointmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcApplication1.AppointmentReference.AppointmentStatu AppointmentStatuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<MvcApplication1.AppointmentReference.AppointmentStatu> AppointmentStatuReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AppointmentStatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcApplication1.AppointmentReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<MvcApplication1.AppointmentReference.User> UserReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppointmentID {
            get {
                return this.AppointmentIDField;
            }
            set {
                this.AppointmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcApplication1.AppointmentReference.AppointmentStatu AppointmentStatu {
            get {
                return this.AppointmentStatuField;
            }
            set {
                this.AppointmentStatuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<MvcApplication1.AppointmentReference.AppointmentStatu> AppointmentStatuReference {
            get {
                return this.AppointmentStatuReferenceField;
            }
            set {
                this.AppointmentStatuReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AppointmentStatusID {
            get {
                return this.AppointmentStatusIDField;
            }
            set {
                this.AppointmentStatusIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Date {
            get {
                return this.DateField;
            }
            set {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                this.TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcApplication1.AppointmentReference.User User {
            get {
                return this.UserField;
            }
            set {
                this.UserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserID {
            get {
                return this.UserIDField;
            }
            set {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<MvcApplication1.AppointmentReference.User> UserReference {
            get {
                return this.UserReferenceField;
            }
            set {
                this.UserReferenceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppointmentStatu", Namespace="http://schemas.datacontract.org/2004/07/Common", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class AppointmentStatu : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AppointmentStatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcApplication1.AppointmentReference.Appointment> AppointmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AppointmentStatusID {
            get {
                return this.AppointmentStatusIDField;
            }
            set {
                this.AppointmentStatusIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcApplication1.AppointmentReference.Appointment> Appointments {
            get {
                return this.AppointmentsField;
            }
            set {
                this.AppointmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Common", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class User : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcApplication1.AppointmentReference.Appointment> AppointmentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcApplication1.AppointmentReference.Town TownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TownIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<MvcApplication1.AppointmentReference.Town> TownReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcApplication1.AppointmentReference.UserRole UserRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserRoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<MvcApplication1.AppointmentReference.UserRole> UserRoleReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcApplication1.AppointmentReference.Appointment> Appointments {
            get {
                return this.AppointmentsField;
            }
            set {
                this.AppointmentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseName {
            get {
                return this.HouseNameField;
            }
            set {
                this.HouseNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseNumber {
            get {
                return this.HouseNumberField;
            }
            set {
                this.HouseNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin {
            get {
                return this.PinField;
            }
            set {
                this.PinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcApplication1.AppointmentReference.Town Town {
            get {
                return this.TownField;
            }
            set {
                this.TownField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TownID {
            get {
                return this.TownIDField;
            }
            set {
                this.TownIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<MvcApplication1.AppointmentReference.Town> TownReference {
            get {
                return this.TownReferenceField;
            }
            set {
                this.TownReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcApplication1.AppointmentReference.UserRole UserRole {
            get {
                return this.UserRoleField;
            }
            set {
                this.UserRoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserRoleID {
            get {
                return this.UserRoleIDField;
            }
            set {
                this.UserRoleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<MvcApplication1.AppointmentReference.UserRole> UserRoleReference {
            get {
                return this.UserRoleReferenceField;
            }
            set {
                this.UserRoleReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Town", Namespace="http://schemas.datacontract.org/2004/07/Common", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Town : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MvcApplication1.AppointmentReference.Country CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<MvcApplication1.AppointmentReference.Country> CountryReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Town1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TownIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcApplication1.AppointmentReference.User> UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MvcApplication1.AppointmentReference.Country Country {
            get {
                return this.CountryField;
            }
            set {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CountryID {
            get {
                return this.CountryIDField;
            }
            set {
                this.CountryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<MvcApplication1.AppointmentReference.Country> CountryReference {
            get {
                return this.CountryReferenceField;
            }
            set {
                this.CountryReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Town1 {
            get {
                return this.Town1Field;
            }
            set {
                this.Town1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TownID {
            get {
                return this.TownIDField;
            }
            set {
                this.TownIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcApplication1.AppointmentReference.User> Users {
            get {
                return this.UsersField;
            }
            set {
                this.UsersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRole", Namespace="http://schemas.datacontract.org/2004/07/Common", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class UserRole : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserRole1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserRoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcApplication1.AppointmentReference.User> UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserRole1 {
            get {
                return this.UserRole1Field;
            }
            set {
                this.UserRole1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserRoleID {
            get {
                return this.UserRoleIDField;
            }
            set {
                this.UserRoleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcApplication1.AppointmentReference.User> Users {
            get {
                return this.UsersField;
            }
            set {
                this.UsersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://schemas.datacontract.org/2004/07/Common", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Country : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Country1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<MvcApplication1.AppointmentReference.Town> TownsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country1 {
            get {
                return this.Country1Field;
            }
            set {
                this.Country1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryID {
            get {
                return this.CountryIDField;
            }
            set {
                this.CountryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MvcApplication1.AppointmentReference.Town> Towns {
            get {
                return this.TownsField;
            }
            set {
                this.TownsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppointmentReference.IAppointmentsService")]
    public interface IAppointmentsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentsService/GetAppointment", ReplyAction="http://tempuri.org/IAppointmentsService/GetAppointmentResponse")]
        MvcApplication1.AppointmentReference.Appointment GetAppointment(int appid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentsService/AddAppointment", ReplyAction="http://tempuri.org/IAppointmentsService/AddAppointmentResponse")]
        void AddAppointment(MvcApplication1.AppointmentReference.Appointment a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentsService/ChangeStatus", ReplyAction="http://tempuri.org/IAppointmentsService/ChangeStatusResponse")]
        void ChangeStatus(int appid, int statusid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentsService/DoWork", ReplyAction="http://tempuri.org/IAppointmentsService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentsService/GetAppointmentsNeedingReview", ReplyAction="http://tempuri.org/IAppointmentsService/GetAppointmentsNeedingReviewResponse")]
        System.Collections.Generic.List<MvcApplication1.AppointmentReference.Appointment> GetAppointmentsNeedingReview();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppointmentsService/SendEmail", ReplyAction="http://tempuri.org/IAppointmentsService/SendEmailResponse")]
        void SendEmail(string destinationaddress, string body);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppointmentsServiceChannel : MvcApplication1.AppointmentReference.IAppointmentsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppointmentsServiceClient : System.ServiceModel.ClientBase<MvcApplication1.AppointmentReference.IAppointmentsService>, MvcApplication1.AppointmentReference.IAppointmentsService {
        
        public AppointmentsServiceClient() {
        }
        
        public AppointmentsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppointmentsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppointmentsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppointmentsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MvcApplication1.AppointmentReference.Appointment GetAppointment(int appid) {
            return base.Channel.GetAppointment(appid);
        }
        
        public void AddAppointment(MvcApplication1.AppointmentReference.Appointment a) {
            base.Channel.AddAppointment(a);
        }
        
        public void ChangeStatus(int appid, int statusid) {
            base.Channel.ChangeStatus(appid, statusid);
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Collections.Generic.List<MvcApplication1.AppointmentReference.Appointment> GetAppointmentsNeedingReview() {
            return base.Channel.GetAppointmentsNeedingReview();
        }
        
        public void SendEmail(string destinationaddress, string body) {
            base.Channel.SendEmail(destinationaddress, body);
        }
    }
}
